name: Package exe for PyInstaller - Windows/Linux

on: [push]
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/main.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Draft Board Tool'
          options: --onefile, --name "Draft Board Tool", --windowed, 
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/main.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Draft Board Tool'
          options: --onefile, --name "Draft Board Tool", --windowed, 